server:
  port: 9003
spring:
  application:
    name: zuul-service
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7000.com:7000/eureka/
  instance:
    health-check-url-path: /actuator/health
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
zuul:
  routes:
    api-feign:
      path: /feign/**
      serviceId: feign-server
    api-rest:
      path: /ribbon/**
      serviceId: ribbon-server